/* Editori */
INSERT INTO editore (id, nazione, nome, path_immagine) VALUES(nextval('editore_seq'), 'Italia', 'J-POP', '/images/Editore_images/J-POP.jpg')
INSERT INTO editore (id, nazione, nome, path_immagine) VALUES(nextval('editore_seq'), 'Italia', 'Planet Manga', '/images/Editore_images/planet_manga.jpg')
INSERT INTO editore (id, nazione, nome, path_immagine) VALUES(nextval('editore_seq'), 'Italia', 'Star Comics', '/images/Editore_images/star_comics.jpg')

/* Manga, "In Corso" or "Terminato" */
INSERT INTO manga (id, titolo, numero_volumi, autore, ongoing, path_immagine) VALUES(nextval('manga_seq'), 'Tokyo Ghoul', 16, 'Sui Ishida', 'Terminato', '/images/Manga_images/J-POP/tokyo_ghoul.jpg')
INSERT INTO manga (id, titolo, numero_volumi, autore, ongoing, path_immagine) VALUES(nextval('manga_seq'), 'Tokyo Ghoul:Re', 14, 'Sui Ishida', 'Terminato', '/images/Manga_images/J-POP/tokyo_ghoul_re.jpg')
INSERT INTO manga (id, titolo, numero_volumi, autore, ongoing, path_immagine) VALUES(nextval('manga_seq'), 'The Promised Neverland', 20 , 'Kaiu Shirai', 'Terminato', '/images/Manga_images/J-POP/TPN.jpg')

INSERT INTO manga (id, titolo, numero_volumi, autore, ongoing, path_immagine) VALUES(nextval('manga_seq'), 'Bleach', 74, 'Tite Kubo', 'Terminato', '/images/Manga_images/planet_manga/bleach.jpg')
INSERT INTO manga (id, titolo, numero_volumi, autore, ongoing, path_immagine) VALUES(nextval('manga_seq'), 'Death Note', 12, 'Tsugumi Ouba', 'Terminato', '/images/Manga_images/planet_manga/death_note.jpg')
INSERT INTO manga (id, titolo, numero_volumi, autore, ongoing, path_immagine) VALUES(nextval('manga_seq'), 'Spy x Family', 13, 'Tatsuya Endou', 'In Corso', '/images/Manga_images/planet_manga/spy_x_family.jpg')

INSERT INTO manga (id, titolo, numero_volumi, autore, ongoing, path_immagine) VALUES(nextval('manga_seq'), 'Demon Slayer', 23, 'Koyoharu Gotouge', 'Terminato', '/images/Manga_images/star_comics/demon_slayer.jpg')
INSERT INTO manga (id, titolo, numero_volumi, autore, ongoing, path_immagine) VALUES(nextval('manga_seq'), 'My Hero Academia', 40, 'Kouhei Horikoshi', 'In Corso', '/images/Manga_images/star_comics/mha.jpg')

/* Variant */
/*J-POP*/
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('Tokyo Ghoul Black 1', nextval('variant_seq'), '2014-10-30', (SELECT id FROM manga WHERE titolo='Tokyo Ghoul'), 10, 'Nessuno', (SELECT id FROM editore WHERE nome='J-POP'), 1, 'Variant di Tokyo Ghoul 1 rilasciata per il Lucca Comics & Games 2014.', '/images/Variant_images/J-POP/tokyo_ghoul_black_1.png')
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('Tokyo Ghoul Miracle ITA', nextval('variant_seq'), '2016-11-23', (SELECT id FROM manga WHERE titolo='Tokyo Ghoul'), 8, 'Nessuno', (SELECT id FROM editore WHERE nome='J-POP'), 1, 'Variant di Tokyo Ghoul 1 presente in un bundle con l''artbook di Tokyo Ghoul (Zakki) e la prima Light Novel di Tokyo Ghoul.', '/images/Variant_images/J-POP/tokyo_ghoul_miracle.jpg')
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('The Promised Neverland 500 Copie', nextval('variant_seq'), '2018-01-31', (SELECT id FROM manga WHERE titolo='The Promised Neverland'), 10, 'Nessuno', (SELECT id FROM editore WHERE nome='J-POP'), 1, 'Variant di The Promised Neverland 1 ottenibile solo nelle fumetterie o nello store online PopStore.', '/images/Variant_images/J-POP/TPN_500_copie.png')
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('The Promised Neverland Feltrinelli', nextval('variant_seq'), '2022-04-28', (SELECT id FROM manga WHERE titolo='The Promised Neverland'), 4, 'Nessuno', (SELECT id FROM editore WHERE nome='J-POP'), 1, 'Variant di The Promised Neverland 1 ottenibile solo nei negozi Feltrinelli.', '/images/Variant_images/J-POP/TPN_feltrinelli.jpg')

/*Planet Manga*/
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('Bleach 1 ITA', nextval('variant_seq'), '2017-11-02', (SELECT id FROM manga WHERE titolo='Bleach'), 10, 'Lenticolare', (SELECT id FROM editore WHERE nome='Planet Manga'), 1, 'Variant di Bleach 1 ottenibile in tutte le fumetterie e store online in quantità limitatissima.', '/images/Variant_images/planet_manga/bleach.jpg')
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('Death Note Steelbox', nextval('variant_seq'), '2021-01-28', (SELECT id FROM manga WHERE titolo='Death Note'), 10, 'Nessuno', (SELECT id FROM editore WHERE nome='Planet Manga'), 1, 'Variant di Death Note 1 in edizione Steelbox, ottenibile in quantità limitata dallo store Panini', '/images/Variant_images/planet_manga/death_note_steelbox.jpg')
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('Death Note 1 ITA', nextval('variant_seq'), '2023-11-02', (SELECT id FROM manga WHERE titolo='Death Note'), 1, 'Metallizzato-Rilievo', (SELECT id FROM editore WHERE nome='Planet Manga'), 1, 'Variant di Death Note 1 metallizzata, ottenibile senza troppa fretta in tutte le fumetterie e store online.', '/images/Variant_images/planet_manga/death_note_variant_ita_1.jpg')
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('Spy x Family 1 ITA', nextval('variant_seq'), '2020-11-05', (SELECT id FROM manga WHERE titolo='Spy x Family'), 6, 'Nessuno', (SELECT id FROM editore WHERE nome='Planet Manga'), 1, 'Variant di Spy x Family 1, parte di un set da 3 variant dei primi 3 volumi. Raffigura Loid Forger.', '/images/Variant_images/planet_manga/spy_x_family_ita_1.jpg')
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('Spy x Family 2 ITA', nextval('variant_seq'), '2021-01-14', (SELECT id FROM manga WHERE titolo='Spy x Family'), 5, 'Nessuno', (SELECT id FROM editore WHERE nome='Planet Manga'), 2, 'Variant di Spy x Family 2, parte di un set da 3 variant dei primi 3 volumi. Raffigura Anya Forger.', '/images/Variant_images/planet_manga/spy_x_family_ita_2.jpg')
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('Spy x Family 3 ITA', nextval('variant_seq'), '2021-03-11', (SELECT id FROM manga WHERE titolo='Spy x Family'), 4, 'Nessuno', (SELECT id FROM editore WHERE nome='Planet Manga'), 3, 'Variant di Spy x Family 3, parte di un set da 3 variant dei primi 3 volumi. Raffigura Yor Forger.', '/images/Variant_images/planet_manga/spy_x_family_ita_3.jpg')

/*Planet Manga*/
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('Demon Slayer 1 Comicon', nextval('variant_seq'), '2019-04-10', (SELECT id FROM manga WHERE titolo='Demon Slayer'), 8, 'Nessuno', (SELECT id FROM editore WHERE nome='Star Comics'), 1, 'Variant di Demon Slayer 1, ottenibile in copie molto limitate al Napoli Comicon del 2019.', '/images/Variant_images/star_comics/demon_slayer_1_comicon.jpg')
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('Demon Slayer 23 ITA', nextval('variant_seq'), '2023-04-12', (SELECT id FROM manga WHERE titolo='Demon Slayer'), 1, 'Metallizzato-Ruvido', (SELECT id FROM editore WHERE nome='Star Comics'), 23, 'Variant di Demon Slayer 23, ottenibile senza troppa fretta in tutte le fumetterie e store online.', '/images/Variant_images/star_comics/demon_slayer_23_ita.jpg')
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('Demon Slayer 13 ITA', nextval('variant_seq'), '2021-05-12', (SELECT id FROM manga WHERE titolo='Demon Slayer'), 4, 'Nessuno', (SELECT id FROM editore WHERE nome='Star Comics'), 13, 'Variant di Demon Slayer 13, ottenibile in tutte le fumetterie e store online.', '/images/Variant_images/star_comics/demon_slayer_13_ita.jpg')
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('MHA 1 ITA', nextval('variant_seq'), '2016-02-06', (SELECT id FROM manga WHERE titolo='My Hero Academia'), 8, 'Nessuno', (SELECT id FROM editore WHERE nome='Star Comics'), 1, 'Variant di My Hero Academia 1, ottenibile in tutte le fumetterie e store online. La vera difficoltà sta nel trovarne una in buone condizioni... ', '/images/Variant_images/star_comics/mha_variant_1_ita.jpg')
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('MHA 14 ITA', nextval('variant_seq'), '2018-04-26', (SELECT id FROM manga WHERE titolo='My Hero Academia'), 5, 'Nessuno', (SELECT id FROM editore WHERE nome='Star Comics'), 14, 'Variant di My Hero Academia 14, ottenibile in tutte le fumetterie e store online. La vera difficoltà sta nel trovarne una in buone condizioni... ', '/images/Variant_images/star_comics/mha_variant_14_ita.jpeg')
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('MHA 30 ITA', nextval('variant_seq'), '2021-12-01', (SELECT id FROM manga WHERE titolo='My Hero Academia'), 0, 'Nessuno', (SELECT id FROM editore WHERE nome='Star Comics'), 30, 'Variant di My Hero Academia 30, ottenibile senza NESSUNA fretta in tutte le fumetterie e store online. Soprannominata "il mattone", è una delle variant più emblematiche della storia, per la sua fama di essere un vero e proprio "mattone di collezionismo", vista la facilità con cui si trova ancora in giro, e ha acquisito meno valore del volume regolare. ', '/images/Variant_images/star_comics/mha_mattone_30.jpeg')
INSERT INTO variant (nome_variant, id, data_uscita, manga_id, rarità, effetto_copertina, editore_id, volume, descrizione, path_immagine) VALUES('MHA 39 ITA', nextval('variant_seq'), '2024-04-23', (SELECT id FROM manga WHERE titolo='My Hero Academia'), 2, 'Nessuno', (SELECT id FROM editore WHERE nome='Star Comics'), 39, 'Variant di My Hero Academia 39, ottenibile in tutte le fumetterie e store online.', '/images/Variant_images/star_comics/mha_39_ita.jpeg')
